# Luigi Toscano <luigi.toscano@tiscali.it>, 2016. #zanata
# Luigi Toscano <luigi.toscano@tiscali.it>, 2017. #zanata
# Giovanni Grieco <giovanni.grc96@gmail.com>, 2018. #zanata
msgid ""
msgstr ""
"Project-Id-Version: PACKAGE VERSION\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2020-03-19 15:27+0100\n"
"PO-Revision-Date: 2018-04-30 08:21+0000\n"
"Last-Translator: Giovanni Grieco <giovanni.grc96@gmail.com>\n"
"Language-Team: Italian\n"
"Language: it\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=2; plural=(n != 1)\n"
"X-Generator: Zanata 4.6.2\n"

#. Translators: This string is only used in unit tests.
#: ../plugins/system_upgrade.py:46
msgid "the color of the sky"
msgstr "il colore del cielo"

#: ../plugins/system_upgrade.py:62
msgid "Need a --releasever greater than the current system version."
msgstr ""
"Richiesto un valore di --releasever maggiore della versione attuale del "
"sistema."

#. Translators: do not change "reboot" here
#: ../plugins/system_upgrade.py:64
#, python-brace-format
msgid ""
"Download complete! Use 'dnf {command} reboot' to start the upgrade.\n"
"To remove cached metadata and transaction use 'dnf {command} clean'"
msgstr ""

#: ../plugins/system_upgrade.py:67
msgid "Sorry, you need to use 'download --releasever' instead of '--network'"
msgstr "Bisogna usare l'opzione 'download --releasever' invece di '--network'"

#: ../plugins/system_upgrade.py:122
#, python-format
msgid "Screen blanking can't be disabled: %s"
msgstr ""

#: ../plugins/system_upgrade.py:143
#, python-format
msgid "Failed loading state file: %s, continuing with empty state."
msgstr ""

#: ../plugins/system_upgrade.py:295
msgid "The following boots appear to contain upgrade logs:"
msgstr ""
"I seguenti precedenti avvii del sistema sembrano contenere dei log di "
"aggiornamenti:"

#: ../plugins/system_upgrade.py:305
msgid "-- no logs were found --"
msgstr "-- nessun log è stato trovato --"

#: ../plugins/system_upgrade.py:320
msgid "Cannot find logs with this index."
msgstr "Impossibile trovare log con questo indice."

#: ../plugins/system_upgrade.py:329
#, fuzzy
msgid "Unable to match systemd journal entry"
msgstr "Non è stato possibile trovare l'inserto sul systemd journal"

#: ../plugins/system_upgrade.py:350
msgid "Prepare system for upgrade to a new release"
msgstr "Prepara il sistema per l'aggiornamento ad una nuova versione"

#: ../plugins/system_upgrade.py:360
msgid "keep installed packages if the new release's version is older"
msgstr ""
"mantiene i pacchetti installati se le versioni del nuovo rilascio sono più "
"vecchie"

#: ../plugins/system_upgrade.py:364
msgid "which logs to show"
msgstr "quali log mostrare"

#: ../plugins/system_upgrade.py:398
#, python-brace-format
msgid "Incompatible version of data. Rerun 'dnf {command} download [OPTIONS]'"
msgstr ""

#: ../plugins/system_upgrade.py:435
msgid "Command 'offline-distrosync' cannot be used with --no-downgrade option"
msgstr ""

#: ../plugins/system_upgrade.py:457
msgid "Additional information for System Upgrade: {}"
msgstr ""

#: ../plugins/system_upgrade.py:460
msgid ""
"Before you continue ensure that your system is fully upgraded by running "
"\"dnf --refresh upgrade\". Do you want to continue"
msgstr ""
"Prima di continuare assicurarsi che il sistema è completamente aggiornato "
"con \"dnf --refresh upgrade\". Procedere"

#: ../plugins/system_upgrade.py:464
msgid "Operation aborted."
msgstr "Operazione annullata."

#: ../plugins/system_upgrade.py:527
msgid "system is not ready for upgrade"
msgstr "il sistema non è pronto per gli aggiornamenti"

#: ../plugins/system_upgrade.py:530
#, python-brace-format
msgid ""
"the transaction was not prepared for '{command}'. Rerun 'dnf {command} "
"download [OPTIONS]'"
msgstr ""

#: ../plugins/system_upgrade.py:534
msgid "upgrade is already scheduled"
msgstr "l'aggiornamento è già pianificato"

#: ../plugins/system_upgrade.py:540
msgid "trigger file does not exist. exiting quietly."
msgstr ""

#: ../plugins/system_upgrade.py:543
msgid "another upgrade tool is running. exiting quietly."
msgstr ""
"un altro strumento di aggiornamento è in esecuzione, uscita silenziosa."

#: ../plugins/system_upgrade.py:552
#, python-brace-format
msgid "use 'dnf {command} reboot' to begin the upgrade"
msgstr ""

#: ../plugins/system_upgrade.py:570
msgid "Rebooting to perform upgrade."
msgstr "Riavvio per effettuare l'aggiornamento."

#: ../plugins/system_upgrade.py:594
msgid "Starting offline upgrade. This will take a while."
msgstr ""

#: ../plugins/system_upgrade.py:596
msgid "Starting offline distrosync. This will take a while."
msgstr ""

#: ../plugins/system_upgrade.py:598
msgid "Starting system upgrade. This will take a while."
msgstr "Avvio dell'aggiornamento del sistema. Ci vorrà un po'."

#: ../plugins/system_upgrade.py:630 ../plugins/system_upgrade.py:639
#, python-format
msgid "Unable to match package: %s"
msgstr "Non è stato possibile trovare il pacchetto %s"

#: ../plugins/system_upgrade.py:644
msgid "Unable to match some of packages"
msgstr "Non è stato possibile trovare alcuni pacchetti"

#: ../plugins/system_upgrade.py:647
msgid "Cleaning up downloaded data..."
msgstr "Pulizia dei dati scaricati..."

#: ../plugins/system_upgrade.py:725
msgid "Download finished."
msgstr "Scaricamento completato."

#: ../plugins/system_upgrade.py:729 ../plugins/system_upgrade.py:730
msgid "Upgrade complete! Cleaning up and rebooting..."
msgstr "Aggiornamento completato! Pulizia e riavvio in corso..."

#: ../plugins/system_upgrade.py:739
msgid "Prepare offline upgrade of the system"
msgstr ""

#: ../plugins/system_upgrade.py:744
msgid "Prepare offline distrosync of the system"
msgstr ""

#: ../plugins/tracer.py:70
msgid "For more information run:"
msgstr "Per maggiori informazioni eseguire:"

#: ../plugins/tracer.py:97
msgid "Call to Tracer API ended unexpectedly:"
msgstr "La chiamata all'API di Tracer è terminata in modo inaspettato:"

#: ../plugins/tracer.py:99
msgid ""
"Please visit https://github.com/FrostyX/tracer/issues and submit the issue. "
"Thank you"
msgstr ""
"Visitare https://github.com/FrostyX/tracer/issues e segnalare il problema.\n"
"Grazie"

#: ../plugins/tracer.py:101
msgid "We apologize for any inconvenience"
msgstr "Ci scusiamo per i disagi"

#: ../plugins/rpm_conf.py:65
msgid "Adding '{}' to list of handling packages for rpmconf"
msgstr "Aggiunta di '{}' all'elenco di pacchetti da far gestire a rpmconf"

#: ../plugins/rpm_conf.py:71
msgid "rpmconf plugin will not run in non-interactive mode"
msgstr "il plugin rpmconf non verrà eseguito in modalità non-interattiva"

#: ../plugins/rpm_conf.py:84
msgid "ignoring sys.exit from rpmconf due to missing MERGE variable"
msgstr ""
"viene ignorata la chiamata a sys.exit di rpmconf dovuta alla variable MERGE "
"mancante"

#: ../plugins/rpm_conf.py:88
msgid "ignoring sys.exit from rpmconf due to missing file"
msgstr ""
"viene ignorata la chiamata a sys.exit di rpmconf dovuta ad un file mancante"

#: ../plugins/showvars.py:46
msgid "show all active dnf variables"
msgstr ""

#: ../plugins/snapper.py:49
#, python-format
msgid "connect to snapperd failed: %s"
msgstr "connessione a snapperd non riuscita: %s"

#: ../plugins/snapper.py:55
msgid "creating pre_snapshot"
msgstr ""

#: ../plugins/snapper.py:61
#, python-format
msgid "created pre_snapshot %d"
msgstr ""

#: ../plugins/snapper.py:65
#, python-format
msgid "creating pre_snapshot failed: %s"
msgstr ""

#: ../plugins/snapper.py:74
msgid "skipping post_snapshot because creation of pre_snapshot failed"
msgstr ""

#: ../plugins/snapper.py:80
msgid "creating post_snapshot"
msgstr ""

#: ../plugins/snapper.py:85
#, python-format
msgid "created post_snapshot %d"
msgstr ""

#: ../plugins/snapper.py:89
#, python-format
msgid "creating post_snapshot failed: %s"
msgstr ""

#: ../plugins/kickstart.py:60
msgid "Install packages defined in a kickstart file on your system"
msgstr "Installa i pacchetti definiti in un file kickstart sul sistema"

#: ../plugins/kickstart.py:65
msgid "kickstart file"
msgstr "File di kickstart"

#: ../plugins/kickstart.py:83
#, python-format
msgid "file cannot be parsed: %s"
msgstr "il file non può essere analizzato: %s"

#: ../plugins/torproxy.py:31
msgid "Disabling torproxy plugin: cannot connect to the Tor network"
msgstr ""
"Il plugin torproxy è stato disabilitato: impossibile connettersi alla rete "
"Tor"
